apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
          # config map에서 원하는 데이터만 불러올 때 사용
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_ROOT_PASSWORD
